[package]
name = "penrose_menu"
version = "0.1.1"
authors = ["IDAM <innes.andersonmorrison@gmail.com>"]
edition = "2018"

[dependencies]
fuzzy-matcher = "0.3"
log = "0.4"
penrose = { path = "../../" }
